server.port: 8787
spring.application.name: springboot-mybatis
spring.profiles.active: dev

#数据库配置
spring.datasource.username: root
spring.datasource.password: root
spring.datasource.url: jdbc:mysql://localhost:3306/20191024hyb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
spring.datasource.driver-class-name: com.mysql.jdbc.Driver

spring.jpa.database : MYSQL
spring.jpa.show-sql : true
spring.jpa.hibernate.ddl-auto : update
spring.jpa.hibernate.naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
spring.jpa.properties.hibernate.dialect : org.hibernate.dialect.MySQL5Dialect

mybatis.mapper-locations: classpath:mapping/*Mapper.xml
mybatis.type-aliases-package: com.rails.entity
 
logging.level.com.rails : debug
